"""Canonical writer for ~/.config/dino/config.toml.

Both `dino setup` (full first-run) and `dino auth` (swap one credential) share
this module so the file format stays consistent across both code paths.

We hand-format TOML rather than pulling in `tomli_w` because the schema is
small and stable.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover — only triggers on Python 3.10
    import tomli as tomllib

_HEADER = "# Generated by `dino setup` / `dino auth`. Edit by hand at your own risk."


def config_path() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "dino" / "config.toml"


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _quote(value: str) -> str:
    return f'"{_toml_escape(value)}"'


def load_dict() -> dict:
    """Read the existing config file as a plain dict, or {} if absent.

    Does NOT raise on missing/empty fields — that's `config.load()`'s job.
    """
    path = config_path()
    if not path.is_file():
        return {}
    with path.open("rb") as fh:
        return tomllib.load(fh)


def write(
    *,
    api_key: str,
    model: str = "whisper-1",
    language: str | None = None,
    prompt: str | None = None,
    timeout_seconds: float = 30.0,
    tui_language: str = "es",
    tui_lifecycle: str = "exec-once",
    tui_terminal: str | None = None,
    output_adapter: str = "wl-copy",
) -> Path:
    """Write the canonical config.toml with mode 0600. Returns the path."""
    path = config_path()
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [_HEADER, "", "[whisper]"]
    lines.append(f"api_key = {_quote(api_key)}")
    lines.append(f"model = {_quote(model)}")
    if language:
        lines.append(f"language = {_quote(language)}")
    if prompt:
        lines.append(f"prompt = {_quote(prompt)}")
    lines.append(f"timeout_seconds = {timeout_seconds:g}")

    lines += ["", "[tui]"]
    lines.append(f"language = {_quote(tui_language)}")
    lines.append(f"lifecycle = {_quote(tui_lifecycle)}")
    if tui_terminal:
        lines.append(f"terminal = {_quote(tui_terminal)}")

    lines += ["", "[output]"]
    lines.append(f"adapter = {_quote(output_adapter)}")
    lines.append("")

    path.write_text("\n".join(lines))
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
    return path
