"""Interactive first-run setup.

Runs as `dino setup`. Asks the user which STT provider to configure, captures the
API key, writes `~/.config/dino/config.toml` with restrictive permissions, and
optionally appends Hyprland push-to-talk bindings.

Heavy imports (rich, questionary) live inside `run()` so the hot-path commands
(`start`, `stop`, `toggle`) don't pay the startup cost on every keypress.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

from dino import __version__

_CONFIG_HEADER = "# Generated by `dino setup`. Edit by hand at your own risk."

# Providers shown in the wizard. Only `openai` is wired up in v0.1; the rest are
# rendered as disabled menu entries so users see the roadmap from day one.
_PROVIDERS: list[dict] = [
    {
        "key": "openai",
        "label": "OpenAI Whisper",
        "status": "available",
        "blurb": "$0.006/min · 99 languages · 1-3s latency",
    },
    {
        "key": "groq",
        "label": "Groq Whisper",
        "status": "v0.2",
        "blurb": "Free tier · ~200ms latency · same Whisper engine",
    },
    {
        "key": "deepgram",
        "label": "Deepgram Nova-3",
        "status": "v0.2",
        "blurb": "$0.0043/min · <300ms streaming · English-first",
    },
    {
        "key": "assemblyai",
        "label": "AssemblyAI Universal-1",
        "status": "v0.2",
        "blurb": "Diarization · $0.12/h batch",
    },
    {
        "key": "local",
        "label": "Local whisper.cpp",
        "status": "v0.3",
        "blurb": "Offline · private · CPU/GPU dependent",
    },
]


def _config_path() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "dino" / "config.toml"


def _hypr_config_path() -> Path | None:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    path = Path(base) / "hypr" / "hyprland.conf"
    return path if path.is_file() else None


def _running_under_hyprland() -> bool:
    return bool(os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"))


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def run() -> int:
    # Lazy imports keep `dino start` / `stop` fast on every hotkey press.
    import questionary
    from questionary import Choice
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt
    from rich.table import Table

    console = Console()

    console.print(
        Panel.fit(
            f"[bold cyan]dino[/bold cyan] [dim]v{__version__}[/dim]\n"
            "Push-to-talk voice dictation for Wayland.",
            border_style="cyan",
        )
    )
    console.print()

    # ── Step 1: pick a provider ──────────────────────────────────────────────
    table = Table(title="Available STT providers", title_style="bold", show_lines=False)
    table.add_column("Provider", style="cyan")
    table.add_column("Status")
    table.add_column("Notes", style="dim")
    for p in _PROVIDERS:
        status_style = "green" if p["status"] == "available" else "yellow"
        table.add_row(p["label"], f"[{status_style}]{p['status']}[/{status_style}]", p["blurb"])
    console.print(table)
    console.print()

    choices = [
        Choice(
            title=f"{p['label']}  ({p['status']})",
            value=p["key"],
            disabled=None if p["status"] == "available" else "coming soon",
        )
        for p in _PROVIDERS
    ]

    provider = questionary.select(
        "Which provider do you want to configure?",
        choices=choices,
        instruction="(use ↑ ↓, Enter to confirm)",
    ).ask()

    if provider is None:
        console.print("[red]Setup cancelled.[/red]")
        return 1

    # ── Step 2: collect provider-specific credentials ────────────────────────
    if provider != "openai":
        console.print(
            f"[yellow]{provider}[/yellow] is on the roadmap. "
            "For now this wizard only configures OpenAI."
        )
        return 1

    api_key = Prompt.ask(
        "[bold]OpenAI API key[/bold] (input hidden)",
        password=True,
    ).strip()

    if not api_key or not api_key.startswith("sk-"):
        console.print("[red]That doesn't look like a valid OpenAI key (should start with 'sk-').[/red]")
        return 1

    model = questionary.select(
        "Whisper model?",
        choices=[
            Choice("whisper-1  (default, cheapest, $0.006/min)", value="whisper-1"),
            Choice("gpt-4o-mini-transcribe  (better WER, slightly more)", value="gpt-4o-mini-transcribe"),
            Choice("gpt-4o-transcribe  (best WER, most expensive)", value="gpt-4o-transcribe"),
        ],
    ).ask()
    if model is None:
        return 1

    language = Prompt.ask(
        "Primary language (ISO-639-1, empty = auto-detect)",
        default="es",
    ).strip()

    prompt = Prompt.ask(
        "Vocabulary prompt (terms the model should know — empty to skip)",
        default="",
    ).strip()

    # ── Step 3: write config.toml ────────────────────────────────────────────
    config_path = _config_path()
    config_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [_CONFIG_HEADER, "", "[whisper]"]
    lines.append(f'api_key = "{_toml_escape(api_key)}"')
    lines.append(f'model = "{model}"')
    if language:
        lines.append(f'language = "{_toml_escape(language)}"')
    if prompt:
        lines.append(f'prompt = "{_toml_escape(prompt)}"')
    lines.append("")

    config_path.write_text("\n".join(lines))
    config_path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600

    console.print()
    console.print(f"[green]✓[/green] Wrote [cyan]{config_path}[/cyan] (mode 600)")

    # ── Step 4: offer Hyprland binding ───────────────────────────────────────
    if _running_under_hyprland() or _hypr_config_path():
        if Confirm.ask(
            "Hyprland detected. Append push-to-talk binding (SUPER+V) to your hyprland.conf?",
            default=True,
        ):
            _append_hyprland_binding(console)
    else:
        console.print(
            "[dim]Hyprland not detected — see "
            "[link]https://github.com/thsergitox/dino/blob/main/docs/HYPRLAND_SETUP.md[/link] "
            "for binding instructions on your compositor.[/dim]"
        )

    # ── Done ─────────────────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel.fit(
            "[green]Setup complete.[/green]\n\n"
            "Try it now:\n"
            "  [cyan]dino start[/cyan]   (talk for a few seconds)\n"
            "  [cyan]dino stop[/cyan]    (transcribes and types into the focused window)",
            border_style="green",
        )
    )
    return 0


def _append_hyprland_binding(console) -> None:
    from rich.prompt import Confirm

    path = _hypr_config_path()
    if path is None:
        console.print("[yellow]No ~/.config/hypr/hyprland.conf found — skipped.[/yellow]")
        return

    snippet = (
        "\n# dino — push-to-talk dictation (added by `dino setup`)\n"
        "bind  = SUPER, V, exec, dino start\n"
        "bindr = SUPER, V, exec, dino stop\n"
    )

    existing = path.read_text()
    if "dino start" in existing:
        console.print("[yellow]Binding already present in hyprland.conf — skipped.[/yellow]")
        return

    if not Confirm.ask(
        f"Append the following to [cyan]{path}[/cyan]?\n[dim]{snippet}[/dim]",
        default=True,
    ):
        return

    with path.open("a") as fh:
        fh.write(snippet)
    console.print(f"[green]✓[/green] Appended binding to [cyan]{path}[/cyan]")
    console.print("[dim]Run `hyprctl reload` to activate.[/dim]")
