"""Interactive first-run setup.

Runs as `dino setup`. Asks the user for STT provider, OpenAI API key, model,
language hint, vocabulary prompt, UI language, and process lifecycle
(`exec-once` vs lazy-spawn), then writes `~/.config/dino/config.toml` and
optionally appends the Hyprland scratchpad block (SUPER+Z).

Heavy imports (rich, questionary) live inside `run()` so the hot-path commands
(`start`, `stop`, `toggle`) don't pay the startup cost on every keypress.
"""

from __future__ import annotations

import os
import platform
import shutil
import stat
import textwrap
from pathlib import Path

from dino import __version__

_CONFIG_HEADER = "# Generated by `dino setup`. Edit by hand at your own risk."

# Providers shown in the wizard. Only `openai` is wired up in v0.2; the rest are
# rendered as disabled menu entries so users see the roadmap from day one.
_PROVIDERS: list[dict] = [
    {
        "key": "openai",
        "label": "OpenAI Whisper",
        "status": "available",
        "blurb": "$0.006/min · 99 languages · 1-3s latency",
    },
    {
        "key": "groq",
        "label": "Groq Whisper",
        "status": "v0.3",
        "blurb": "Free tier · ~200ms latency · same Whisper engine",
    },
    {
        "key": "deepgram",
        "label": "Deepgram Nova-3",
        "status": "v0.3",
        "blurb": "$0.0043/min · <300ms streaming · English-first",
    },
    {
        "key": "assemblyai",
        "label": "AssemblyAI Universal-1",
        "status": "v0.3",
        "blurb": "Diarization · $0.12/h batch",
    },
    {
        "key": "local",
        "label": "Local whisper.cpp",
        "status": "v0.3",
        "blurb": "Offline · private · CPU/GPU dependent",
    },
]


def _config_path() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "dino" / "config.toml"


def _hypr_config_path() -> Path | None:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    path = Path(base) / "hypr" / "hyprland.conf"
    return path if path.is_file() else None


def _running_under_hyprland() -> bool:
    return bool(os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"))


def _distro_id() -> str:
    """Best-effort distro ID via /etc/os-release."""
    try:
        info = platform.freedesktop_os_release()
    except (OSError, AttributeError):
        return ""
    return (info.get("ID") or "").lower()


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def run() -> int:
    # Lazy imports keep `dino start` / `stop` fast on every hotkey press.
    import questionary
    from questionary import Choice
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt
    from rich.table import Table

    from dino.terminal import build_launch_cmd, detect as detect_terminal

    console = Console()

    console.print(
        Panel.fit(
            f"[bold cyan]dino[/bold cyan] [dim]v{__version__}[/dim]\n"
            "Voice dictation TUI for Hyprland.",
            border_style="cyan",
        )
    )
    console.print()

    # ── Step 1: pick a provider ──────────────────────────────────────────────
    table = Table(title="Available STT providers", title_style="bold", show_lines=False)
    table.add_column("Provider", style="cyan")
    table.add_column("Status")
    table.add_column("Notes", style="dim")
    for p in _PROVIDERS:
        status_style = "green" if p["status"] == "available" else "yellow"
        table.add_row(p["label"], f"[{status_style}]{p['status']}[/{status_style}]", p["blurb"])
    console.print(table)
    console.print()

    provider = questionary.select(
        "¿Qué proveedor STT querés configurar?",
        choices=[
            Choice(
                title=f"{p['label']}  ({p['status']})",
                value=p["key"],
                disabled=None if p["status"] == "available" else "coming soon",
            )
            for p in _PROVIDERS
        ],
        instruction="(↑ ↓ y Enter)",
    ).ask()

    if provider is None:
        console.print("[red]Setup cancelado.[/red]")
        return 1
    if provider != "openai":
        console.print(f"[yellow]{provider}[/yellow] está en el roadmap. Por ahora solo OpenAI.")
        return 1

    # ── Step 2: OpenAI credentials ──────────────────────────────────────────
    api_key = Prompt.ask(
        "[bold]OpenAI API key[/bold] (oculto)",
        password=True,
    ).strip()

    if not api_key or not api_key.startswith("sk-"):
        console.print("[red]La key no parece válida (debe empezar con 'sk-').[/red]")
        return 1

    model = questionary.select(
        "¿Modelo Whisper?",
        choices=[
            Choice("whisper-1  (default, más barato, $0.006/min)", value="whisper-1"),
            Choice("gpt-4o-mini-transcribe  (mejor WER, un poco más caro)", value="gpt-4o-mini-transcribe"),
            Choice("gpt-4o-transcribe  (mejor WER, más caro)", value="gpt-4o-transcribe"),
        ],
    ).ask()
    if model is None:
        return 1

    language = Prompt.ask(
        "Idioma principal (ISO-639-1, vacío = auto-detect)",
        default="es",
    ).strip()

    prompt = Prompt.ask(
        "Prompt de vocabulario (términos para sesgar al modelo — vacío para omitir)",
        default="",
    ).strip()

    # ── Step 3: TUI preferences ─────────────────────────────────────────────
    tui_language = questionary.select(
        "¿Idioma de la TUI?",
        choices=[
            Choice("Español (default)", value="es"),
            Choice("English", value="en"),
        ],
    ).ask()
    if tui_language is None:
        return 1

    lifecycle = questionary.select(
        "¿Cómo se lanza el proceso dino en Hyprland?",
        choices=[
            Choice(
                "exec-once — dino se inicia con Hyprland y siempre está listo (~50MB RAM idle).",
                value="exec-once",
            ),
            Choice(
                "lazy-spawn — script que lanza dino la primera vez que pulsas SUPER+Z.",
                value="lazy",
            ),
        ],
    ).ask()
    if lifecycle is None:
        return 1

    # ── Step 4: detect terminal ─────────────────────────────────────────────
    term_spec = detect_terminal()
    if term_spec is None:
        console.print(
            "[yellow]No se detectó ninguna terminal soportada (kitty/alacritty/foot/ghostty/wezterm)."
            "Voy a guardar la config igual, pero tendrás que editar a mano el comando exec-once.[/yellow]"
        )
    else:
        console.print(f"[green]✓[/green] Terminal detectada: [cyan]{term_spec.binary}[/cyan]")

    # ── Step 5: write config.toml ───────────────────────────────────────────
    config_path = _config_path()
    config_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [_CONFIG_HEADER, "", "[whisper]"]
    lines.append(f'api_key = "{_toml_escape(api_key)}"')
    lines.append(f'model = "{model}"')
    if language:
        lines.append(f'language = "{_toml_escape(language)}"')
    if prompt:
        lines.append(f'prompt = "{_toml_escape(prompt)}"')

    lines += ["", "[tui]"]
    lines.append(f'language = "{tui_language}"')
    lines.append(f'lifecycle = "{lifecycle}"')

    lines += ["", "[output]"]
    lines.append('adapter = "wl-copy"')
    lines.append("")

    config_path.write_text("\n".join(lines))
    config_path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
    console.print()
    console.print(f"[green]✓[/green] Escribí [cyan]{config_path}[/cyan] (mode 600)")

    # ── Step 6: Hyprland binding ────────────────────────────────────────────
    if _running_under_hyprland() or _hypr_config_path():
        if Confirm.ask(
            "¿Agregar el bloque scratchpad (SUPER+Z) a tu hyprland.conf?",
            default=True,
        ):
            _append_hyprland_block(console, term_spec, lifecycle)
    else:
        console.print(
            "[dim]Hyprland no detectado — mirá "
            "[link]https://github.com/thsergitox/dino/blob/main/docs/HYPRLAND_SETUP.md[/link] "
            "para configurarlo en tu compositor.[/dim]"
        )

    # ── Step 7: clipboard persistence (wl-clip-persist) ─────────────────────
    if _running_under_hyprland() or _hypr_config_path():
        _maybe_setup_clipboard_persistence(console)

    # ── Done ────────────────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel.fit(
            "[green]Setup listo.[/green]\n\n"
            "Probalo ahora:\n"
            "  [cyan]dino[/cyan]   (lanza la TUI)\n"
            "  o, en Hyprland, pulsá [cyan]SUPER+Z[/cyan].",
            border_style="green",
        )
    )
    return 0


def _build_hyprland_block(term_spec, lifecycle: str) -> str:
    """Generate the lines we'll append to hyprland.conf."""
    if term_spec is None:
        exec_cmd = "$TERMINAL --class dino -e dino tui"
    else:
        exec_cmd = " ".join(build_launch_cmd_safe(term_spec, ["dino", "tui"]))

    common_rules = textwrap.dedent(
        """\
        windowrule = workspace special:dino silent, class:^(dino)$
        windowrule = float, class:^(dino)$
        windowrule = size 60% 50%, class:^(dino)$
        windowrule = center 1, class:^(dino)$
        """
    )

    if lifecycle == "exec-once":
        return (
            "\n# dino — voice dictation TUI (added by `dino setup`)\n"
            f"exec-once = {exec_cmd}\n\n"
            f"{common_rules}\n"
            "bind = SUPER, Z, togglespecialworkspace, dino\n"
        )

    # lazy-spawn: ship a tiny wrapper script.
    return (
        "\n# dino — voice dictation TUI (lazy-spawn, added by `dino setup`)\n"
        f"{common_rules}\n"
        "bind = SUPER, Z, exec, ~/.config/dino/dino-toggle.sh\n"
    )


def build_launch_cmd_safe(spec, inner):
    """Wrapper used by _build_hyprland_block — kept separate for unit tests."""
    from dino.terminal import build_launch_cmd

    return build_launch_cmd(spec, inner)


def _write_lazy_toggle_script(term_spec) -> Path:
    """Render `~/.config/dino/dino-toggle.sh` for lazy-spawn lifecycle."""
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    script_path = Path(base) / "dino" / "dino-toggle.sh"
    script_path.parent.mkdir(parents=True, exist_ok=True)

    if term_spec is None:
        launch_line = '$TERMINAL --class dino -e dino tui &'
    else:
        launch_line = " ".join(build_launch_cmd_safe(term_spec, ["dino", "tui"])) + " &"

    script_path.write_text(textwrap.dedent(
        f"""\
        #!/usr/bin/env bash
        # dino lazy-spawn toggle — generated by `dino setup`.
        # Launches dino on first invocation, then toggles the special workspace.
        set -euo pipefail

        if ! hyprctl clients -j | grep -q '"class": "dino"'; then
            {launch_line}
            # Give the window time to appear before the dispatcher toggles it.
            sleep 0.4
        fi
        hyprctl dispatch togglespecialworkspace dino >/dev/null
        """
    ))
    script_path.chmod(0o755)
    return script_path


def _append_hyprland_block(console, term_spec, lifecycle: str) -> None:
    path = _hypr_config_path()
    if path is None:
        console.print("[yellow]No hay ~/.config/hypr/hyprland.conf — omitido.[/yellow]")
        return

    block = _build_hyprland_block(term_spec, lifecycle)

    existing = path.read_text()
    if "togglespecialworkspace, dino" in existing or "dino-toggle.sh" in existing:
        console.print("[yellow]Ya hay un bloque dino en hyprland.conf — omitido.[/yellow]")
        return

    from rich.prompt import Confirm  # local import; rich is already imported in run()

    console.print(f"[dim]Voy a agregar a [cyan]{path}[/cyan]:[/dim]")
    console.print(f"[dim]{block}[/dim]")
    if not Confirm.ask("¿Confirmás?", default=True):
        return

    with path.open("a") as fh:
        fh.write(block)
    console.print(f"[green]✓[/green] Bloque agregado a [cyan]{path}[/cyan]")

    if lifecycle == "lazy":
        script_path = _write_lazy_toggle_script(term_spec)
        console.print(f"[green]✓[/green] Script lazy escrito en [cyan]{script_path}[/cyan]")

    console.print("[dim]Ejecutá `hyprctl reload` para activar.[/dim]")


def _maybe_setup_clipboard_persistence(console) -> None:
    """Detect `wl-clip-persist` and offer to wire it into hyprland.conf.

    Without `wl-clip-persist`, anything copied via `wl-copy` disappears the
    moment the Wayland session ends (logout, reboot). The daemon keeps the
    clipboard alive across that boundary by holding onto the selection.
    """
    from rich.prompt import Confirm  # rich is already loaded by run()

    path = _hypr_config_path()
    if path is None:
        return

    existing = path.read_text()
    if "wl-clip-persist" in existing:
        console.print("[dim]wl-clip-persist ya está configurado en hyprland.conf.[/dim]")
        return

    has_binary = shutil.which("wl-clip-persist") is not None

    console.print()
    if not has_binary:
        console.print(
            "[yellow]Tip:[/yellow] sin [cyan]wl-clip-persist[/cyan], lo que copies con dino "
            "se pierde al cerrar la sesión Wayland."
        )
        distro = _distro_id()
        if distro in ("arch", "manjaro", "endeavouros", "cachyos"):
            console.print(
                "  Instalación: [bold]paru -S wl-clip-persist-bin[/bold] "
                "(o yay -S wl-clip-persist-bin) — está en AUR."
            )
        elif distro in ("debian", "ubuntu", "pop", "linuxmint"):
            console.print(
                "  Instalación: [bold]cargo install wl-clip-persist[/bold] "
                "o descargá un release prebuilt de "
                "[link]https://github.com/Linus789/wl-clip-persist/releases[/link]"
            )
        elif distro in ("fedora", "nobara", "rhel"):
            console.print(
                "  Instalación: [bold]cargo install wl-clip-persist[/bold] "
                "o descargá un release prebuilt de "
                "[link]https://github.com/Linus789/wl-clip-persist/releases[/link]"
            )
        else:
            console.print(
                "  Releases prebuilt: "
                "[link]https://github.com/Linus789/wl-clip-persist/releases[/link]"
            )
        console.print(
            "[dim]Después instalarlo, volvé a correr `dino setup` para que te agregue "
            "el exec-once a hyprland.conf.[/dim]"
        )
        return

    # Binary is installed — offer to wire it up.
    if not Confirm.ask(
        "¿Activar [cyan]wl-clip-persist[/cyan] al iniciar Hyprland para que el clipboard "
        "sobreviva al cerrar sesión?",
        default=True,
    ):
        return

    block = (
        "\n# wl-clip-persist — keep clipboard alive across Wayland sessions "
        "(added by `dino setup`)\n"
        "exec-once = wl-clip-persist\n"
    )
    with path.open("a") as fh:
        fh.write(block)
    console.print(
        f"[green]✓[/green] Agregado [cyan]wl-clip-persist[/cyan] a [cyan]{path}[/cyan]"
    )
    console.print(
        "[dim]Empieza a tomar efecto en la próxima sesión Wayland, o ejecutá manualmente "
        "`wl-clip-persist &` ahora.[/dim]"
    )
